Refactor php72 service

diff --git a/php72/Dockerfile b/php72/Dockerfile
--- a/php72/Dockerfile
+++ b/php72/Dockerfile
@@ -1,36 +1,240 @@
 FROM php:7.2-fpm
 
-COPY php.ini /usr/local/etc/php/
+LABEL maintainer="Emerson Max <emersonmx@gmail.com>"
 
-RUN apt-get update \
-    && apt-get install -y \
-        libfreetype6-dev libjpeg62-turbo-dev libpng-dev libxml2-dev \
-        libicu-dev zlib1g-dev postgresql-server-dev-all \
-        libmagickwand-dev git vim locales unzip \
-    && sed -i 's/^\#[ \t]*en_US\(.*\)/en_US\1/' /etc/locale.gen \
-    && sed -i 's/^\#[ \t]*pt_\(.*\)/pt_\1/' /etc/locale.gen \
+RUN set -xe; \
+    apt-get update -yqq && \
+    pecl channel-update pecl.php.net && \
+    apt-get install -yqq \
+        apt-utils \
+        libzip-dev zip unzip && \
+        docker-php-ext-configure zip --with-libzip; \
+        docker-php-ext-install zip && \
+        php -m | grep -q 'zip'
+
+
+###########################################################################
+# bcmath:
+###########################################################################
+
+ARG INSTALL_BCMATH=false
+
+RUN if [ ${INSTALL_BCMATH} = true ]; then \
+    # Install the bcmath extension
+    docker-php-ext-install bcmath \
+;fi
+
+###########################################################################
+# Mysqli Modifications:
+###########################################################################
+
+ARG INSTALL_MYSQLI=false
+
+RUN if [ ${INSTALL_MYSQLI} = true ]; then \
+    docker-php-ext-install mysqli \
+;fi
+
+###########################################################################
+# Human Language and Character Encoding Support:
+###########################################################################
+
+ARG INSTALL_INTL=false
+
+RUN if [ ${INSTALL_INTL} = true ]; then \
+    # Install intl and requirements
+    apt-get install -y zlib1g-dev libicu-dev g++ && \
+    docker-php-ext-configure intl && \
+    docker-php-ext-install intl \
+;fi
+
+###########################################################################
+# ImageMagick:
+###########################################################################
+
+USER root
+
+ARG INSTALL_IMAGEMAGICK=false
+
+RUN if [ ${INSTALL_IMAGEMAGICK} = true ]; then \
+    apt-get install -y libmagickwand-dev imagemagick && \
+    pecl install imagick && \
+    docker-php-ext-enable imagick \
+;fi
+
+###########################################################################
+# Opcache:
+###########################################################################
+
+ARG INSTALL_OPCACHE=false
+
+RUN if [ ${INSTALL_OPCACHE} = true ]; then \
+    docker-php-ext-install opcache \
+;fi
+
+# Copy opcache configration
+COPY ./opcache.ini /usr/local/etc/php/conf.d/opcache.ini
+
+###########################################################################
+# Image optimizers:
+###########################################################################
+
+USER root
+
+ARG INSTALL_IMAGE_OPTIMIZERS=false
+
+RUN if [ ${INSTALL_IMAGE_OPTIMIZERS} = true ]; then \
+    apt-get install -y jpegoptim optipng pngquant gifsicle \
+;fi
+
+###########################################################################
+# PHP REDIS EXTENSION
+###########################################################################
+
+ARG INSTALL_PHPREDIS=false
+
+RUN if [ ${INSTALL_PHPREDIS} = true ]; then \
+    pecl install -o -f redis && \
+    rm -rf /tmp/pear && \
+    docker-php-ext-enable redis \
+;fi
+
+###########################################################################
+# BZ2:
+###########################################################################
+
+ARG INSTALL_BZ2=false
+RUN if [ ${INSTALL_BZ2} = true ]; then \
+    apt-get -y install libbz2-dev; \
+    docker-php-ext-install bz2 \
+;fi
+
+###########################################################################
+# SOAP:
+###########################################################################
+
+ARG INSTALL_SOAP=false
+
+RUN if [ ${INSTALL_SOAP} = true ]; then \
+    # Install the soap extension
+    rm /etc/apt/preferences.d/no-debian-php && \
+    apt-get -y install libxml2-dev php-soap && \
+    docker-php-ext-install soap \
+;fi
+
+###########################################################################
+# XSL:
+###########################################################################
+
+ARG INSTALL_XSL=false
+
+RUN if [ ${INSTALL_XSL} = true ]; then \
+    # Install the xsl extension
+    apt-get -y install libxslt-dev && \
+    docker-php-ext-install xsl \
+;fi
+
+###########################################################################
+# Exif:
+###########################################################################
+
+ARG INSTALL_EXIF=false
+
+RUN if [ ${INSTALL_EXIF} = true ]; then \
+    # Enable Exif PHP extentions requirements
+    docker-php-ext-install exif \
+;fi
+
+###########################################################################
+# pgsql
+###########################################################################
+
+ARG INSTALL_PGSQL=false
+
+RUN apt search postgresql-server-dev
+RUN if [ ${INSTALL_PGSQL} = true ]; then \
+    apt-get -y install postgresql-server-dev-11 && \
+    # Install the pgsql extension
+    docker-php-ext-install pgsql \
+;fi
+
+###########################################################################
+# pcntl
+###########################################################################
+
+ARG INSTALL_PCNTL=false
+RUN if [ ${INSTALL_PCNTL} = true ]; then \
+    # Installs pcntl, helpful for running Horizon
+    docker-php-ext-install pcntl \
+;fi
+
+###########################################################################
+# GETTEXT:
+###########################################################################
+
+ARG INSTALL_GETTEXT=false
+
+RUN if [ ${INSTALL_GETTEXT} = true ]; then \
+    apt-get install -y zlib1g-dev libicu-dev g++ libpq-dev libssl-dev gettext && \
+    docker-php-ext-install gettext \
+;fi
+
+###########################################################################
+# Install additional locales:
+###########################################################################
+
+ARG INSTALL_ADDITIONAL_LOCALES=false
+ARG ADDITIONAL_LOCALES
+
+RUN if [ ${INSTALL_ADDITIONAL_LOCALES} = true ]; then \
+    apt-get install -y locales \
+    && echo '' >> /usr/share/locale/locale.alias \
+    && temp="${ADDITIONAL_LOCALES%\"}" \
+    && temp="${temp#\"}" \
+    && for i in ${temp}; do sed -i "/$i/s/^#//g" /etc/locale.gen; done \
     && locale-gen \
-    && docker-php-ext-install -j$(nproc) \
-        iconv intl zip bcmath pcntl exif soap \
-        pdo_pgsql pgsql pdo_mysql mysqli \
-    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
-    && docker-php-ext-install -j$(nproc) gd \
-    && printf "\n" | pecl install imagick-beta \
-    && docker-php-ext-enable imagick \
-    && apt-get remove -y \
-        libfreetype6-dev libjpeg62-turbo-dev libpng-dev libxml2-dev \
-        libicu-dev zlib1g-dev postgresql-server-dev-all \
-        libmagickwand-dev \
-    && apt-get install -y libfreetype6 libjpeg62-turbo libpng16-16 \
-        libicu63 libltdl7 zlib1g libpq5 libxml2 \
-        libmagickwand-6.q16-6 \
-        iproute2 \
-    && rm -rf /var/lib/apt/lists/* \
-    && apt-get autoremove -y
+;fi
 
-RUN \
+###########################################################################
+# composer
+###########################################################################
+
+ARG INSTALL_COMPOSER=false
+RUN if [ ${INSTALL_COMPOSER} = true ]; then \
     curl -sS https://getcomposer.org/installer | php && \
     mv composer.phar /usr/local/bin/composer && \
-    composer self-update
+    composer self-update && \
+    composer global require hirak/prestissimo \
+;fi
+
+#
+#--------------------------------------------------------------------------
+# Final Touch
+#--------------------------------------------------------------------------
+#
+
+COPY ./laravel.ini /usr/local/etc/php/conf.d
+COPY ./xlaravel.pool.conf /usr/local/etc/php-fpm.d/
+
+USER root
+
+# Clean up
+RUN apt-get clean && \
+    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && \
+    rm /var/log/lastlog /var/log/faillog
+
+# Configure non-root user.
+ARG PUID=1000
+ENV PUID ${PUID}
+ARG PGID=1000
+ENV PGID ${PGID}
+
+RUN groupmod -o -g ${PGID} www-data && \
+    usermod -o -u ${PUID} -g www-data www-data
+
+# Configure locale.
+ARG LOCALE=POSIX
+ENV LC_ALL ${LOCALE}
+
+WORKDIR /var/www
 
 EXPOSE 9000
